namespace: default
resources:
  - nginx.yaml
  - mariadb.yaml
  - backend.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - configs/init.sql
secretGenerator:
- name: database-creds
  files:
  - jwtKey.txt